export const text = {
  play: 'Play',
  moreInfo: 'More Info',
  views: 'Views',
  likes: 'Likes',
  becomeCreator: 'Become a Creator',
  becomeCreatorMessage:
    'Create your own animations thanks to incredible animation tool - FlipaClip Animation Studio.',
  explore: 'Explore',
  creators: 'Creators',
  more: 'More',
  less: 'Less',
  downloadProject: 'Download Project',
  creatorsSite: 'Creators Site',
  favoriteBrushes: 'Favorite Brushes',
  sendRequest: 'Send a request',
  createYourOwnAnimations:
    'Create your own animations thanks to incredible animation tool - FlipaClip Animation Studio',
  name: 'Name',
  email: 'Email',
  link: 'Link',
  thankYou: 'Thank you',
  pageDoesNotExist: 'The page you are looking for does not exist.',
  videoDoesNotExist: 'The video you are looking for does not exist.',
  creatorDoesNotExist: 'The creator you are looking for does not exist.',
  applicationError: 'An error occurred while processing your request.',
  checkThisVideoOut: 'Check this video out!',
};
