export const text = {
  play: 'Play',
  moreInfo: 'More Info',
  views: 'Views',
  likes: 'Likes',
  becomeCreator: 'Submit Your Movie',
  submit: 'Submit',
  becomeCreatorMessage:
    'Share your animated story with us for a chance to be featured in FLIPS.',
  explore: 'Explore',
  share: 'Share',
  creators: 'Creators',
  more: 'More',
  less: 'Less',
  downloadProject: 'Download Project',
  creatorsSite: 'Creators Site',
  favoriteBrushes: 'Favorite Brushes',
  sendRequest: 'Send a request',
  createYourOwnAnimations:
    'Create your own animations thanks to incredible animation tool - FlipaClip Animation Studio',
  includeLink: 'Please include a link to your movie below.',
  name: 'Name',
  email: 'Email',
  link: 'Link',
  woohoo: 'Woohoo! 🎞️',
  thanks:
    'Thanks for submitting your movie. We will review it and get back to you soon. Stay tuned!',
  pageDoesNotExist: 'The page you are looking for does not exist.',
  webIsNotSupported: `Thanks for stopping by! The web version of our app isn't available yet, but we're working hard to bring it to you soon!`,
  videoDoesNotExist: 'The video you are looking for does not exist.',
  creatorDoesNotExist: 'The creator you are looking for does not exist.',
  applicationError: 'An error occurred while processing your request.',
  checkThisVideoOut: 'Check this video out!',
};
